name: ec2 deploy 2

on:
  push:
    branches: ["master"]

  workflow_dispatch:


permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'

    - name: permission grant to gradlew
      run: chmod +x gradlew

    - name: jar build
      uses: gradle/gradle-build-action@v2.6.0
      with:
        arguments: -x test build
        cache-read-only: ${{ github.ref != 'refs/heads/main' && github.ref != 'refs/heads/develop' }}

    - name: build jar upload
      uses: actions/upload-artifact@v2
      with:
        name: ride_server
        path: build/libs/RIDE_PROJECT-0.0.1-SNAPSHOT.jar


  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: download jar
        uses: actions/download-artifact@v2
        with:
          name: ride_server
          path: build/libs

      - name: deploy to ec2
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          scp -i private_key.pem -o StrictHostKeyChecking=no build/libs/RIDE_PROJECT-0.0.1-SNAPSHOT.jar ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:/home/${{ secrets.EC2_USERNAME }}/ride_server.jar
          ssh -i private_key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "pgrep java | xargs kill -9; nohup java -jar /home/${{ secrets.EC2_USERNAME }}/ride_server.jar > app.log 2>&1 &"
          rm -f private_key.pem



